### ISSUE TITLE
After leveling/choosing 30 fetishes, you can no longer access the fetish screen

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#433] opened 2018-05-03 19:15 UTC
**Version** : 0.2.4.5
**From** : Patreon
**Date** : 3 May 2018

**Comment by Pimvgd** [comment] 2018-05-06 09:30
Tested on ad09d08835661cc5c983016a31025e52f79e4652 (0.2.4.5), could not reproduce. See attached savefiles; one has 37/38 fetishes chosen, the other one 38/38. Both get into the fetish screen fine.

[saves-for-433.zip](https://github.com/Innoxia/liliths-throne-public/files/1977487/saves-for-433.zip)

**Comment by Pimvgd** [comment] 2018-05-13 20:06
Tested with Kar Dragon on Discord, who seems to have a similar issue. I came to the conclusion that the fetish screen without any fetishes unlocked has about 16 MB of input string on the stack at its worst, whereas the fetish screen with all the fetishes unlocked is sitting at about 121 MB. #472 and #475 reduced this to 74 MB, leading me to believe that it's worth waiting to see if and what changes with the new upcoming version.

**Comment by Rfpnj** [comment] 2018-05-13 20:45
Running LT while in the Java mission control gave some interesting reading when it came to the Java dump Memory and the fetish screen. I entered the screen and the memory load dropped.

**Comment by Pimvgd** [comment] 2018-05-13 20:47
That just means that the garbage collector ran because it ran out of memory and thus started to clean old stuff up to make space.

**Comment by Pimvgd** [comment] 2018-06-07 18:59
Fixed with UtilText.parse iterative, since the stack traces I have found for this are due to memory.

**Closed** 2018-06-07 19:00 UTC
