### ISSUE TITLE
Rooms "Garden Rooom GG-20" and "Room G-32" are being loaded as empty rooms.

### ISSUE THREAD

**Issue by DerMaskierte** [Innoxia/liliths-throne-public#462] opened 2018-05-10 19:52 UTC
[Bug.zip](https://github.com/Innoxia/liliths-throne-public/files/1996050/Bug.zip)
[Bug.zip](https://github.com/Innoxia/liliths-throne-public/files/1996051/Bug.zip)

In version 0.2.5, the two rooms over the library reset when I load a game.

The rooms are called "Garden Rooom GG-20" and "Room G-32" by default.

The first thing I tried was starting a new game to check if it was a corrupt save since I loaded from version 0.2.4, but it still happens.

Checking the save data it shows it's saved properly, and the changes to the rooms look like the other rooms, the problem happens when the rooms are loaded. Slaves are still assigned to those rooms, but any properties the room had are erased and returned to an Empty Room state. 

I tried different combinations of room presets, and nothing worked. I find strange no one else is having this problem, so I tried re-downloading the game, and all versions .jar, x64 exe and x32 exe, But it happens with all of them. The information of those two rooms in the save file is simply being ignored when loaded.

I changed all rooms in the house and then saved and loaded, and only those two rooms appear to be affected.
[Bug.zip](https://github.com/Innoxia/liliths-throne-public/files/1996052/Bug.zip)

I attached a save in which one of the rooms has been upgraded to a single bedroom and the other is empty. Loading it results in both being empty. I do not think the problem is in the save, but it is all I can do at this time.

**Comment by DerMaskierte** [comment] 2018-05-10 21:35
Forgot about that. A 0 KB empty file. Wasn't event accessed.

**Comment by MarianSijanin** [comment] 2018-05-11 06:01
Confirmed, **0.2.5**. 
GG-06 and G-10 in my save:
[https://mega.nz/#!vlgggBgR!MmDUBPDXRidkDDwbEJpr3T0DkEWk-KRKiLLQwJ_Zp_4](url)
Cells deserialized ok, but upgrades cleared after that somehow...

**Comment by Innoxia** [comment] 2018-05-11 19:30
Thank you for the reports! This was occurring due to an old method in map generation, which was clearing room upgrades upon loading. This is fixed in 0.2.5.5. ^^

**Closed by Innoxia** 2018-05-11 19:30 UTC
