### ISSUE TITLE
Taking Inventory From Arcane Arts

### ISSUE THREAD

**Issue by EsHoshizora** [Innoxia/liliths-throne-public#1369] opened 2020-07-23 05:05 UTC
When enchanting items while trading with Vicky doing the same enchantment until you run out of items will put you back on the inventory trading screen, but will allow you to use the "take all" button to take everything in Vicky's inventory. This works for both the "weapons" and the "spells & potions" inventories, but was not tested on other shopkeeps.

Taking all of Vicky's items was unexpected, as the button should have stayed grayed out during the trading interactions.

1. Go to Ralph's Snacks and purchase an amount of an enchantable item (tested it with several of the transforming foods) or otherwise have a quantity on hand
2. Go to Arcane Arts and begin trading with Vicky and open either the weapons or spells & potions inventory menus
3. Select one of the enchantable items and open the enchanting menu by clicking the button in the corner
4. Select the random enchantment and select craft
5. Continue selecting craft until the item is all used up
6. without moving the mouse from that position, click again when the normal trading inventory screen reappears (the take all button is in the same space as the craft button)
7. The error then occurs, allowing you to take all of Vicky's inventory (this works on both weapons and spells & potions)

Error Code?:

Failed to load character present home: 14,DominionAlleywayAttacker
Failed to load character present home: 13,DominionAlleywayAttacker
Failed to load character present home: 12,DominionAlleywayAttacker
Failed to load character present home: 10,DominionAlleywayAttacker
Failed to load character present home: 11,DominionAlleywayAttacker
java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(Unknown Source)
	at java.awt.image.Raster.createPackedRaster(Unknown Source)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(Unknown Source)
	at java.awt.image.BufferedImage.<init>(Unknown Source)
	at com.lilithsthrone.rendering.CachedImage.scaleDown(CachedImage.java:131)
	at com.lilithsthrone.rendering.CachedImage.load(CachedImage.java:35)
	at com.lilithsthrone.rendering.ImageCache.getImage(ImageCache.java:98)
	at com.lilithsthrone.game.character.GameCharacter.getCharacterInformationScreen(GameCharacter.java:3113)
	at com.lilithsthrone.game.dialogue.utils.CharactersPresentDialogue.resetContent(CharactersPresentDialogue.java:42)
	at com.lilithsthrone.controller.MainControllerInitMethod.lambda$4(MainControllerInitMethod.java:391)
	at com.lilithsthrone.controller.MainControllerInitMethod$$Lambda$601/10918643.handleEvent(Unknown Source)
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:814)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
	at javafx.scene.web.WebView$$Lambda$103/32714567.handle(Unknown Source)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
var timer not found...
var timer not found...

**Additional information:**
 - Game version 3.8.9 Alpha
 - OS: Windows 10
 - Using .jar or .exe: .jar

Screenshots:

![image](https://user-images.githubusercontent.com/68677524/88253472-13e6e280-cc80-11ea-8d54-8a7d5fe58a41.png)
![image](https://user-images.githubusercontent.com/68677524/88253530-48f33500-cc80-11ea-944c-ba835e5e12f4.png)
![image](https://user-images.githubusercontent.com/68677524/88253557-5a3c4180-cc80-11ea-9ca9-d90b8537e5a6.png)
![image](https://user-images.githubusercontent.com/68677524/88253570-66c09a00-cc80-11ea-9479-64e7e38500e0.png)
![image](https://user-images.githubusercontent.com/68677524/88253582-704a0200-cc80-11ea-96b1-ba3767af16ca.png)

**Comment by AceXP** [comment] 2020-07-25 11:00
It's possible to reproduce this with all shopkeepers. It happens when crafting and you enchant the last item, so not really necessary to have a stack of items, just one is enough. Also, it's not limited to take all, you can also do 'displace all' and 'unequip all' of the hapless shopkeepers clothing (or take all their flames, if they had any).
No OutOfMemoryError for me, so that is not the issue here.
To keep things simple, I'd suggest that the option to enchant an item be removed when trading. Same as during sex and combat. Then again, Dye/Reforge actions work as intended and return you to the normal dialogue, so it should be possible to do the same for enchanting. Thoughts?

**Comment by AceXP** [comment] 2020-08-10 08:00
This should have been fixed in version 0.3.8.6, but I can confirm that this is still possible in the latest version.

**Comment by AceXP** [comment] 2020-08-28 09:54
This has been fixed in version 0.3.9.1, could you check it and close this issue?

**Closed** 2020-08-28 11:05 UTC
