### ISSUE TITLE
issue launching 3.20

### ISSUE THREAD

**Issue by Sadmun** [Innoxia/liliths-throne-public#1532] opened 2021-04-05 22:59 UTC
When launching any version of 3.20 (Jar, exe, 32-bit exe) I am unable to select any menu options with mouse or keyboard. I am unable to start a new game by clicking "new game" or pressing 1 on my keyboard. Is this a problem on my end or have other people experienced this bug?

**Comment by AceXP** [comment] 2021-04-06 04:50
Is there anything in the error.log? (Can be found in the data folder). Are you using any mods? If so, does it work without mods?

The issue you describe is usually caused by mods throwing an error.

**Comment by Sadmun** [comment] 2021-04-06 10:49
No mods, guess you could say I play "vanilla".
Error log in data:
Version: 0.3.20
Java: 1.8.0_172
Could this be a Java problem?

**Comment by AceXP** [comment] 2021-04-06 18:55
Not sure what could be the matter. I've not heard this before. Did the earlier version(s) work? It takes a while for the game to start, did you wait for that?

**Comment by Sadmun** [comment] 2021-04-07 01:22
I think the problem was on my end, a fresh download functions perfectly. Sorry for the false alarm and thanks for the assistance.

**Comment by AceXP** [comment] 2021-04-07 04:48
Good to hear it.

Could you please close this issue then? Only Inno or the issue creator can close issues.

**Closed as completed** 2021-04-15 08:15 UTC
