### ISSUE TITLE
Tiny Inventory UI

### ISSUE THREAD

**Issue by tockity** [Innoxia/liliths-throne-public#366] opened 2018-04-19 22:18 UTC
I updated my java today and now I have a tiny little inventory for ants. It's only this size when my inventory is simply open or when I'm looking at a defeated NPC's inventory - when inspecting an item or browsing a shop it's the normal size.

Issue is occurring in both 0.2.3.1 and 0.2.3.5.

Tiny - https://puu.sh/A6EiX/478adb14be.png
Normal - https://puu.sh/A6Eij/d65fa90608.png

**Comment by A-Master-of-Puppets** [comment] 2018-04-19 23:42
I don't think Java 10 is supported yet.

**Comment by tockity** [comment] 2018-04-20 01:16
I think I'm only on Java 8.

https://puu.sh/A6JTv/bbbf98ee91.png

**Comment by A-Master-of-Puppets** [comment] 2018-04-20 01:38
I'm surprised it even _runs_ on Java 8; you should be using Java 9.

**Comment by tockity** [comment] 2018-04-20 05:59
Huh. Java 8's what both the Java and Oracle sites' download/update links sent me to. Figured that was the latest, or at least the current stable version. Strangely, there are download links for 8 and 10 all over the place but nothing for 9. 

Anywho, tried updating to 10 and no change to the original issues.

**Comment by AlacoGit** [comment] 2018-04-20 06:03
Java 10 is indeed the latest version, Java 9 is no longer available from Oracle.

At some point LT is either going to have to move to Java 10 and fix the issues or start directing people to the openJDK [archives](http://jdk.java.net/archive/) to get Java 9.

**Comment by Rfpnj** [comment] 2018-04-20 12:24
OK, after running some tests the issue is a great deal bigger then expected, the reported issue effects all new versions of Java. 8.172, 10.0.1 and I would imagine java 9 as well. Oracle made some change to the JavaFX files to cause the issue and it's not going to be an easy fix.

@Innoxia

**Comment by AlacoGit** [comment] 2018-04-20 12:27
I don't get this issue on Java 9.0.4

**Comment by pervyrogue** [comment] 2018-04-22 20:34
Found that the issue is related to the flavor text of a selected object. This is likely because the div for the inventory screen is nested to the selected object screen which is changing dynamically to the text instead of the window.

**Comment by Garnetxx** [comment] 2018-04-24 06:39
Java 9.0.4 is available through their archives:
http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase9-3934878.html

**Comment by Innoxia** [comment] 2018-04-26 17:39
Thank you all for reporting this! The problem was in the file: 
https://github.com/Innoxia/liliths-throne-public/blob/master/src/com/lilithsthrone/res/css/webView_stylesheet.css

The issue was that `.div-center` was not defining a `width:100%;`, so when an item didn't have enough description text to pad out the width to 100%, it was shrinking down to the smallest size possible. ^^

This will be fixed in 0.2.4 (coming out in 2 days). ^^

**Closed by Innoxia** 2018-04-26 17:39 UTC
