### ISSUE TITLE
Not possible to talk with Lyssieth after getting the perk; stuck in the palace.

### ISSUE THREAD

**Issue by interlamer** [Innoxia/liliths-throne-public#1247] opened 2019-12-27 07:31 UTC
**Describe the bug**
After bringing Lyssieth to Lilaya's home to discuss the plan, then going to Lyssieth's palace to receive the perk, I tried to go back and talk to Lyssieth (I want to turn into a demon). However, I got stuck in the tile with Meraxis. I press 'Enter" and nothing seems to happen. When I press 'Leave', it plays out the dialogue.
**Expected behavior**
It's expected that I would be able to get past the tile with Meraxis upon pressing 'Enter'.
**To Reproduce**
1. Complete the main story until the point where you get the 'Lyssieth's power" perk.
2. Go to Lyssieth's palace, to the tile with Meraxis
3. Press the 'Enter" button
4. Press the 'Leave' button

**Additional information:**
 - Game version: 0.3.5.8
 - OS: Windows 10
 - Using .exe version

**Log file:**
[error.log](https://github.com/Innoxia/liliths-throne-public/files/4004613/error.log)

**Comment by Stadler76** [comment] 2019-12-27 11:19
This would be fixed by PR #1245

**Comment by xPURExRain** [comment] 2019-12-27 12:44
Having same issue with latest build. Loaded up old save and tried to talk to her. Wont prompt normal menu, instead does nothing until attempting to leave. When leave is clicked a bunch of text from when you ask about lunnate is shown.

**Comment by interlamer** [comment] 2019-12-27 18:53
I didn't mean to say that perks matter, I just wanted to show the exact place in the main story when it happened to me. Sorry if it wasn't clear, English is not my native language.

**Comment by Innoxia** [comment] 2019-12-29 22:16
Fixed by merge of #1245

**Closed by Innoxia** 2019-12-29 22:16 UTC

**Comment by Fortilicious** [comment] 2020-01-04 11:29
@ Innoxia, dunno if this is important info, but I'm not seeing it discussed, so I'm posting this just in case it has an impact on the fix you mentioned.

  What I'm experiencing is that the event _is_ proceeding, but it's not _showing_.  While you are 'stuck' in the room, none of the graphical interface is changing, but when you mouse over the spaces where options normally are, hovertext descriptions for actions with Lyssieth are appearing in the proper spots, meaning the game isn't allowing you to move because you are in a conversation with Lyssieth.  Picking one of the actions as normal yields the same results... with the exception that the dialogue is now happening on the game options screen and not in the normal game text field.  Picking a sex option progresses the sex interactions as normal.  After sex, game operation returns to normal.  I was able to reproduce this after shutting down and reloading a save.

Animated Gif link showing the hovertext thing: https://i.gyazo.com/bb0c388c06981bd87e7fd6d08611d284.gif

Screenshot of dialogue with Lyssieth talking about her sister, but on the options screen: https://i.gyazo.com/60a022b1a6f9d6a7aab196590a48fa86.png
