### ISSUE TITLE
Thin walls: sex in an apartment is public

### ISSUE THREAD

**Issue by AceXP** [Innoxia/liliths-throne-public#1224] opened 2019-10-19 08:25 UTC
**Describe the bug**
A companion moved out and into a Dominion tile. When starting sex there, it's marked as public sex and there is a line about spectators and their reaction to the performance.

This only happens right after the move (i.e. when first visiting the allocated tile). When you are visiting again everything works as expected.

**Expected behavior**
Sex in a companion's apartment should always be private.

**To Reproduce**

1. Have a companion move out to their own apartment.
2. Accompany them there (visit apartment option).
3. Start sex.

**Additional information:**
 - Game version [e.g. 0.3.5.1]
 - OS: Windows 10
 - Using .jar, Java: 1.8.0_202

**Comment by Little-119** [comment] 2019-10-26 00:21
It's Not A Bug, It's A Feature™

**Comment by AceXP** [comment] 2019-12-29 13:59
PR Set apartment to true when occupant moves out #1251 will fix this minor issue

**Comment by Innoxia** [comment] 2019-12-29 22:16
Fixed by merge of #1251

**Closed by Innoxia** 2019-12-29 22:16 UTC
