### ISSUE TITLE
"Unknown Command" - Bedroom Dialogue

### ISSUE THREAD

**Issue by nero-Hearts** [Innoxia/liliths-throne-public#1410] opened 2020-09-12 18:46 UTC
**Attach files**
![image](https://user-images.githubusercontent.com/71189618/93002162-1ee52300-f50b-11ea-8e90-da4618d555fd.png)
![image](https://user-images.githubusercontent.com/71189618/93002169-2a384e80-f50b-11ea-9c3f-be99d4ba03ed.png)
![image](https://user-images.githubusercontent.com/71189618/93002170-2efd0280-f50b-11ea-89be-fcf5228317ef.png)
![image](https://user-images.githubusercontent.com/71189618/93002174-3a502e00-f50b-11ea-8af9-7cd3990ede5f.png)

Seems to happen only for slaves with slovenly speech. Apparently only for those with standard, professional or wholesome greeting.

**Additional information:**
version 0.3.9.8
win10
using .jar

**Comment by AceXP** [comment] 2020-09-12 20:11
Thank you for your detailed report. This had been reported before, but the cause was unknown. Now I am able to reproduce, and have found out what is going wrong.

**Comment by AceXP** [comment] 2020-09-19 08:19
This should be fixed in the latest version, can you check it and close this issue?

**Closed** 2020-09-21 05:36 UTC
