### ISSUE TITLE
Incubi transformations not showing during the following sex scenes

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#519] opened 2018-05-21 14:46 UTC
**Version** : 0.2.5.2
**From** : Discord
**Date** : 21 May 2018

![image](https://user-images.githubusercontent.com/23719598/40313580-7d5cda02-5d16-11e8-8b24-09c74316f184.png)

**EDIT : Closed, duplicate of** #490

**Comment by A-Master-of-Puppets** [comment] 2018-05-22 02:17
This looks like a duplicate of #490.

**Comment by A-Master-of-Puppets** [comment] 2018-05-22 04:39
It was actually a problem if _any_ character tried to transform _any_ incubus like that. I guess nobody noticed it before because incubi are rarer than succubi, and perhaps with the full transform menu now available most people use that instead of the quick one.

**Closed** 2018-05-22 10:57 UTC
