### ISSUE TITLE
Broken save

### ISSUE THREAD

**Issue by Twand37** [Innoxia/liliths-throne-public#1120] opened 2019-03-31 07:24 UTC
Dev branch, version 0.3.2.

I'm not entirely sure what's broken here, but before I saved and quit the game, I couldn't open my inventory. Since that was the only thing that appeared noticeably broken, I'd assume that's where the problem is.

When I restarted the game, my save flat out refused to load, and the error log doesn't make it any clearer for me what the problem is. There appears to be several "null" value errors, but I'm having trouble identifying where they're originating.

Here's the error log and save for reference.
[error.log](https://github.com/Innoxia/liliths-throne-public/files/3026299/error.log)
[Tricia.zip](https://github.com/Innoxia/liliths-throne-public/files/3026302/Tricia.zip)

**Comment by DrZed** [comment] 2019-04-12 01:12
👏 if it was my modded version it'd spit out what line it was last reading when it errored. I'm going to push that out into the public build tomorrow so Innoxia can have an easier time fixing those issues...

**Comment by Pimvgd** [comment] 2019-04-20 20:20
You can save your fix by searching for count="null" and replacing the null with 1.

**Comment by Innoxia** [comment] 2019-04-23 21:37
The cause of this error will be fixed in the next update. Thank you for the report!

**Closed by Innoxia** 2019-04-23 21:37 UTC
