### ISSUE TITLE
[0.3.14 alpha] Penis and clit girth can't be maxed out and get stuck at "chubby".

### ISSUE THREAD

**Issue by master9147** [Innoxia/liliths-throne-public#1492] opened 2021-01-20 02:59 UTC
If you take a look at the girth statistic in the buggy menu for both clits and dicks, you see they can't be maxed out to "fat", they just get stuck on "chubby". Keep in mind this is for the unreleased "0.3.14 subspecies leg configuration naming support" build you make yourself on the current GIT as of this writing, Not the current "0.3.13 Hotfix".

**Comment by Stadler76** [comment] 2021-01-23 20:33
Can you please provide more details like: steps to reproduce and so on?
PS: The issue template exists for a reason.

**Comment by Stadler76** [comment] 2021-01-23 22:46
Ok, now I can reproduce your issue.
The fix is simple:
```diff
diff --git a/src/com/lilithsthrone/game/character/body/valueEnums/PenetrationGirth.java b/src/com/lilithsthrone/game/character/body/valueEnums/PenetrationGirth.java
index 7546a94d2..8af28d6e4 100644
--- a/src/com/lilithsthrone/game/character/body/valueEnums/PenetrationGirth.java
+++ b/src/com/lilithsthrone/game/character/body/valueEnums/PenetrationGirth.java
@@ -64,7 +64,7 @@ public enum PenetrationGirth {
 	}
 	
 	public static int getMaximum() {
-		return SIX_CHUBBY.getValue();
+		return SEVEN_FAT.getValue();
 	}
 	
 	public Colour getColour() {
```

I'll ping @Innoxia about that since I don't think we need a PR for a one-line fix.

**Comment by Innoxia** [comment] 2021-01-25 01:42
Thank you for the report, master9147, and for the fix, Stadler! I've got this fixed on my end and will push to dev branch in a few minutes.

**Closed by Innoxia** 2021-01-25 01:42 UTC
