### ISSUE TITLE
inventory bug

### ISSUE THREAD

**Issue by SilentShadow013** [Innoxia/liliths-throne-public#1072] opened 2019-02-25 05:55 UTC
When unequipping items for some inventories it duplicates the item instead of removing it.
it dosent happen to everyone and not every slot.
game version 0.3.0.7

**Comment by CognitiveMist** [comment] 2019-02-25 23:47
Is there anything printed in the error.log

**Comment by SilentShadow013** [comment] 2019-02-26 04:27
> Is there anything printed in the error.log?

it doesnt look like there is but to be honest i dont really know what to look for.

**Comment by CognitiveMist** [comment] 2019-02-26 05:51
Well, if anything appears in the error.log (inside the data folder), it may be relevant. Feel free to attach the whole file here if you want. However, it could be more useful to have a fresh copy: delete or rename the existing log, then go into the game and make the bug happen. Then, upload the new log here.

**Comment by CognitiveMist** [comment] 2019-02-26 06:29
Thanks! Hm, that error log looks like #1046. Maybe that bug is also causing this, or maybe this bug doesn't cause an exception to be hit. Some more investigation is needed to know more, I think.

**Comment by SilentShadow013** [comment] 2019-02-26 07:35
> Thanks! Hm, that error log looks like #1046. Maybe that bug is also causing this, or maybe this bug doesn't cause an exception to be hit. Some more investigation is needed to know more, I think.

its the slot thats getting the bug, i went to the same NPC and their shirt had changed as if to replace the one i took but it still just dupped it when tring to take it.

different characters have different slots bugged even had the underwear slot for one of my characters refuse to unequip. not sure if that is related though.

**Comment by Goldenrevolver** [comment] 2019-03-01 21:59
this bug is connected to enchanting. as soon as you enchant an item of an affected slot the item gets duplicated when you try to equip / remove it (its stuck). 

game version: 0.3.1.01
steps to reproduce: start default new game, have sex for 6 essences, enchant starting ring with cheap enchant, try to equip/ unequip
details: enchant doesnt seem to matter, most slots affected (only thing I could unequip was glasses and weapons but I didnt test all slots)

**Comment by Innoxia** [comment] 2019-03-02 06:27
Thank you all for the reports and feedback! This is fixed in 0.3.1.1.

**Closed by Innoxia** 2019-03-02 06:27 UTC
