### ISSUE TITLE
jinxed item duplicates if removed and un-jinxed (to remove /release seal)

### ISSUE THREAD

**Issue by ton10p** [Innoxia/liliths-throne-public#1302] opened 2020-02-19 01:16 UTC
i had just removed i anal insert with a seal of -5 essence removal cost
after activitys i notest a second one
i also notest i got a notifycation of removing of this item when i only un-sealed my jinxed item
and origonal item remained in equipment slot on my person
somwhere in the code of un-jinxing during intercourse lead to a duplication

**Comment by ton10p** [comment] 2020-02-19 01:36
in last public build, ignore if already addressed

**Comment by AceXP** [comment] 2020-09-15 16:19
I am unable to reproduce this in the latest version, jinxed items cannot be removed without unjinxing. Removing during a sex scene works as intended (and also needs unjinxing first). I cannot see any duplication of items.

Could you check this and close this issue?

**Closed** 2020-09-21 01:45 UTC
