### ISSUE TITLE
Bug preventing from saving

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#971] opened 2018-11-24 05:43 UTC
The save button stops working (confirmation still working, but not the save) and prevents me from saving, making me lose my progress. I'm not sure what is causing the problem, but i think that the heaviest the game becomes, the higher the chance to this bug to happen (happens almost everytime to me).

Since It's difficult to play the game because my notebook is slow, to lose an hour of progress if i forget to save every ten minutes is really annoying. Someone have any idea of what is causing this bug?

Sorry for my english, I'm not an english speaker

**Comment by DrZed** [comment] 2018-12-16 01:19
Are you still having the issues? In an update 8 days ago included a small fix for saving, and autosaves. If not close the thread so the issues section can be cleaned up.

**Comment by RandomNecromancer** [comment] 2018-12-19 00:32
Sorry for the delay, I'll check if the bug still happens as soon as possible.

**Comment by DrZed** [comment] 2018-12-19 00:36
no problem, I'm not the developer, even though I plan to start working on the project and sending updates as soon as I get used to the layout/locations of the code.
It's important to know the flow of the code.

**Comment by RandomNecromancer** [comment] 2018-12-19 03:05
as you mentioned, the bug has been fixed. I had not noticed since I did not have time to play lately because of college tests. thank you for the warning.

**Comment by RandomNecromancer** [comment] 2018-12-31 18:38
it seems that the last update brought the bug back (or i was just lucky and the bug didn't happen on the last version)

**Comment by DrZed** [comment] 2019-01-02 08:49
2 things I need to be able to accurately find the cause, and push a pull request.

1.) What did you do before it happened to lock you out of saving or what were you currently doing when you tried to save

2.)
Java Version : __________ (x86 || x64)  (could influence the issue and could be the cause (if garbage collector is biting the dust))
OS : _________ (x86 || x64) (can help when trying to emulate the issue)
RAM : ________    (Better if you can tell me the % RAM usage at the time trying to save)
Game version : __________ (sanity check)
(CPU shouldn't have anything to do with the issue so don't need it)

Just remember, you cannot save "inside" a building, during sex, during dialogue, or during a fight.
You can only save on Dominion (and maybe Submission IDK never checked there.)

**Comment by DrZed** [comment] 2019-01-02 22:37
1.) I like how you're not a moron and already paid attention to high mem usage, and also already know about garbage collector and java 8+'s remedy to it's old issues. (besides I think the game uses lambda so it'd be impossible to run on 7), 32bit is garbage if you have a 64bit os, excluding the RAM caveat.

It could have a high relation to RAM usage, but garbage collector isn't out of the picture, I'd like to have you use 
`-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`
Just try it it COULD help although a marginal increase in CPU usage will be expected if you can spare it.

to use it make a "startGameExperimental.bat" and put 
"java -jar gameName.jar" and add those -XX args after it

As for a never saved game, the bulk of all the new characters is 1 issue, secondly a question arises what about auto save? Is it working at all?

**Comment by DrZed** [comment] 2019-01-02 23:04
You could simplify the args, by just doing the -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

**Comment by RandomNecromancer** [comment] 2019-01-03 07:33
Autosave does not work after the bug, but on normal occasions it works. As for games already saved, they never corrupted or anything like that.

My notebook is garbage compared to current standards, so I chose to use the 32 bit version exactly because of the RAM memory usage issue. I usually play with no other program open, with avast antivirus disabled, internet disconnected and several useless processes from windows disabled, but even so, as I have only 2 gb of ram, only windows takes up about 50-60% of the ram. The last time I played, after the bug happened the game was using 400mb of ram (in my case, normal usage is about 200-250 mb), about 85% of my computer's total memory. The cpu usage also stopped completely while I was not using it, even though it usually uses a certain amount while the game is not being used (I do not know if that has any relation, though).

Another thing I noticed last time the game bugged was that the button to go upstairs in zaranix's house (I'm not sure that's the name, but it's a npc from the main quest) also suffered from the same save button problem (clickable but nothing happens).

As for the test you asked me to do, does it work regardless of the version or do I need to do some modification to the 32 bit exe version?

**Comment by DrZed** [comment] 2019-01-03 07:36
Sounds almost like the JavaFX thread crashes. it doesn't matter, and it has to be using the jar nothing to do with the EXE.

It might fix the issue still, not sure.

**Comment by DrZed** [comment] 2019-01-03 07:37
Small note, see if you can upgrade the RAM of your notebook it can go a long way with just doubling it as it sits.

**Comment by RandomNecromancer** [comment] 2019-01-03 07:51
I've never done this kind of test so I'm not sure I understood correctly. Since the file to run the game is LT.exe, should I modify the line "java -jar gameName.jar" besides changing the name and extension to the correct ones? or should I not even do it?

sorry for my ignorance...

**Comment by DrZed** [comment] 2019-01-03 07:55
You need to grab the jar version from the blog and put the jar inside the folder you already have of the game, then make the bat file  (make a txt file put java -jar FileName.jar -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M) then rename the txt file to something.bat and doubleclick the bat

**Comment by RandomNecromancer** [comment] 2019-01-03 07:58
oh, I thought I could use the 32 bit exe version. I'm going to download the jar version and test it, sorry for the inconvenience.

**Comment by DrZed** [comment] 2019-01-03 07:59
no problem, I've done this for a long time. I would've quit long before if I haven't dealt with harder situations with language barrier, computer ineptitude and a bit more ontop of the user thinking I don't know what I'm talking about.

**Comment by DrZed** [comment] 2019-01-03 08:01
If you haven't installed Java before though, there is that issue in needing to go install it because a jar can't be run if java isn't installed. (never touched the "windows" exe version so no idea what it does. it could just be a wrapper to simplify starting it)

**Comment by AlacoGit** [comment] 2019-01-03 08:08
If the issue happens again, please check the `data` folder for `error.log` and attach it to the report please.

**Comment by DrZed** [comment] 2019-01-03 08:10
I am going to bed now so I'll see the fruits of your labor tomorrow, and hopefully it does fix the issue. if so Innoxia needs to be notified that it needs to be an optional thing.

Hello random AlacoGit. It hasn't helped entirely for me debugging my own issues :P so I just patched my issues myself after hunting them down. Updating when Innox updates then patching all over again when needed. (haven't pushed a pull request because I'm also doing other changes to do with Localization moving the explicit string literals to a en_US.lang file to work on a translation and translate friendly game that's when I'm pushing my update to Innox)

**Comment by DrZed** [comment] 2019-01-03 08:12
1 Thing I didn't think of and you can fix right away if it is indeed an issue with low RAM environments is the action log (IE picked up x item, y item, z item...), does it cull old entries in a single 1 shot run? if not it can build up a lot.

**Comment by RandomNecromancer** [comment] 2019-01-04 03:47
so ... it looks like I'm not going to be able to answer for sure whether the bug still happens or not. the java version takes up twice as much ram and this ends up making the game too heavy for my notebook. I can still play, but as soon as the ram usage increases and reaches about 600 mb, the game stops responding because my notebook can not handle such heavy programs. as far as I could play the bug did not happen, but considering that the time I can stay in the game before it crashes is considerably smaller than before, I can not guarantee that the bug was actually solved. I'll probably just be able to test if someone somehow finds a way to do this same test on the 32 bit exe version

**Comment by DrZed** [comment] 2019-01-04 04:51
DID you make sure to install ONLY 32x java?
Also you can force it to use less -Xms64m -Xmx400m
add those to the front of the -XX args I gave earlier
(it makes minimum ram usage 64MB and max 400MB you can increase or decrease the numbers as you please)

**Comment by RandomNecromancer** [comment] 2019-01-04 16:57
I did not need to install because I had already installed it. the problem is that I already had both 32-bit and 64-bit versions and I completely forgot about it (a program needed one of those versions specifically, so I had both). I'm almost ashamed of how stupid this situation is. I'll test right now and comment again as soon as I'm sure about the test result.

**Comment by RandomNecromancer** [comment] 2019-01-04 18:48
I did not use those two args you commented on, but I do not think it's going to be necessary, because this time the bug happened before the game even started to use a lot of memory. although the memory consumption is certainly related, since the higher the more likely the bug happens, it seems that this may not be exactly the problem. it seems that it is especially easy for the bug to happen when there are several changes / updates on the screen in a short period of time, because by dyeing several clothes or adding several enchantments into potions the bug seems to almost always happen.

**Comment by DrZed** [comment] 2019-01-04 22:33
Okay, well like AlacoGit said, (don't start the game a second time it empties the log), Give the error_log from the data folder, it could tell us what happened.

**Comment by RandomNecromancer** [comment] 2019-01-05 04:39
[error.log](https://github.com/Innoxia/liliths-throne-public/files/2729155/error.log)

**Comment by DrZed** [comment] 2019-01-05 08:38
`java.lang.OutOfMemoryError: Java heap space`
Done dead jim

**Comment by DrZed** [comment] 2019-01-05 08:42
You got lots of errors
That's going to help us /me
Out of Memory is your issue, that's the diddly.
Specifically heap space which I think you're out of luck on
1 Try systematically killing off processes in your windows that aren't necessary for using windows.
2 like I said earlier look into seeing if your notebook has removable RAM if so upgrade it (DDR3 laptop RAM is tons cheaper than a new book and you should get 4GB for it, as more would probably be incompatible)
3rd option Install (fully install) Lubuntu (most user friendly linux version) onto a flashdrive to play the game
     - or run the live disk of it on a flashdrive and save the game onto your normal drive.

**Comment by DrZed** [comment] 2019-01-05 08:43
4th, if you can try indeed running the jar, in 32bit, and running the parameters I gave above, Literally all of them, it makes garbage collector more aggressive about keeping RAM usage low. Sacrificing cpu which isn't necessary for this game very much anyway.

**Comment by DrZed** [comment] 2019-01-05 08:45
@AlacoGit Grab that error.log It's full of juicy errors
Secondly I was right from the beginning it was RAM issues. I've dealt with them for a decade, I know how to spot them.

**Comment by RandomNecromancer** [comment] 2019-01-07 22:31
I've been trying to run the game with all the arguments you've provided, but so far I've had no luck. I am gradually reducing the amount of maximum memory in the -Xmx argument and testing, but with the small amount of content in a game in version 0.3, this laborious task quickly becomes tedious, so do not expect to receive early news.

I had already disabled several processes and made several modifications to increase the performance of windows, so there is not much to improve on that. I can not afford the cost of a flashdrive or more RAM, since I am a student and in my country, due to taxes, anything you try to buy costs at least five times more than if bought in North America / Europe (importing these products ends up being as bad as or even worse).

it will be great if I can solve the problem through arguments, otherwise I will have to endure this problem, unfortunately. Anyway, thanks for all your help.!(should I close this issue?)

**Comment by DrZed** [comment] 2019-01-07 23:35
Well, anything will work, you could also partition your harddrive and install lubuntu on it, by opening a drive flashing utility to set the partition as a "Bootable Flash Drive" and make it so (only need 4GB partition), and make another partition to ACTUALLY install the OS on which again can be 4-8GB. linux is a good way to restore usability to an old device, besides dual booting Lubuntu/Windows, will allow you to do everything you want.

` -Xms64m -Xmx320m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=10 -XX:G1ReservePercent=10 -XX:MaxGCPauseMillis=20 -XX:G1HeapRegionSize=32M`
Feel free to tweak the percents, and the pausemillis to your hearts content (increase or decrease based on your cpu, if it can handle more, lower the numbers, if it's choking raise them)
If you can't get those to work in your favour any more than they do already then add
` -Dsun.rmi.dgc.server.gcInterval=10000` < that number is in milliseconds so it's at 10 seconds right now instead of the massive delay I set up above (warning this will slow the cpu if you can't handle it only enable if you have a spare 10~ % to use on CPU)

Sucks that you live in such a situation, I wish I could help but I am disabled and live month to month on exactly 771$ thanks to the USA welfare.

**Comment by DrZed** [comment] 2019-01-07 23:36
There is nothing more I can help with given the situation, consider the Lubuntu option, as well as the tweaked args I gave, other than that there's nothing I can do, and you may close this issue now.

**Comment by RandomNecromancer** [comment] 2019-01-08 08:42
just to let you know, the javaFX thread really is crashing... (i'll close the issue again later)
![sem titulo](https://user-images.githubusercontent.com/45304526/50819216-8eefde80-1310-11e9-889c-1fc99ffeb148.png)

**Comment by DrZed** [comment] 2019-01-08 18:50
1 I don't think it can be an odd number (the memory, then again I always used multiples of 16);

**Comment by DrZed** [comment] 2019-01-08 18:53
That moment when it crashes because it crashed because it crashed

**Closed** 2019-01-08 19:48 UTC
