### ISSUE TITLE
Game breaking bug on Amber First Encounter

### ISSUE THREAD

**Issue by HououinK** [Innoxia/liliths-throne-public#1306] opened 2020-02-29 04:17 UTC
**Describe the bug**
On the find Arthur mission, when you first fight Amber if you have sex with her after defeating her the game gets stuck in the moment you cum. Same thing happens with Zaranix i heard.

**Expected behavior**
Should be able to have sex normally with her, but for now the only way to pass the quest is ignoring her after deating her.

**To Reproduce**
Follow the main quest.

**Additional information:**
 Bug happens on 0.361 from the download link from the blog(JAR and EXE) as well as the updated 0.368 from the Git. Couldn't find a version without the bug.

**Comment by Innoxia** [comment] 2020-05-01 12:36
I've tested this on my end (in v0.3.7.3) and can't reproduce this bug. I may have fixed the underlying cause of this bug in a recent update.
I'll close this report, but if you're still encountering this bug in v0.3.7.3, please let me know and I'll reopen this issue.

**Closed by Innoxia** 2020-05-01 12:36 UTC
